drop table if exists gestalt_country_with_name; create table gestalt_country_with_name (id integer, name text, iso2code text, iso3code text);
insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(1,'Bangladesh','BD','BGD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(2,'Bulgaria','BG','BGR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(3,'Namibia','NA','NAM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(4,'Barbados','BB','BRB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(5,'Japan','JP','JPN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(6,'Burundi','BI','BDI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(7,'Bhutan','BT','BTN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(8,'Botswana','BW','BWA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(9,'Brazil','BR','BRA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(10,'Belarus','BY','BLR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(11,'Belize','BZ','BLZ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(12,'Russia','RU','RUS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(13,'Rwanda','RW','RWA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(14,'Serbia','RS','SRB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(15,'Turkmenistan','TM','TKM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(16,'Liberia','LR','LBR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(17,'Romania','RO','ROU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(18,'Guatemala','GT','GTM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(19,'Greece','GR','GRC');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(20,'Equatorial Guinea','GQ','GNQ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(21,'American Samoa','AS','ASM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(22,'Andorra','AD','AND');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(23,'Anguilla','AI','AIA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(24,'Bahrain','BH','BHR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(25,'Guyana','GY','GUY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(26,'French Guiana','GF','GUF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(27,'Georgia','GE','GEO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(28,'United Kingdom','GB','GBR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(29,'Gabon','GA','GAB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(30,'The Gambia','GM','GMB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(31,'Greenland','GL','GRL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(32,'Ghana','GH','GHA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(33,'Oman','OM','OMN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(34,'Jordan','JO','JOR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(35,'Croatia','HR','HRV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(36,'Haiti','HT','HTI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(37,'Hungary','HU','HUN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(38,'Honduras','HN','HND');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(39,'Costa Rica','CR','CRI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(40,'Portugal','PT','PRT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(41,'Paraguay','PY','PRY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(42,'British Indian Ocean Territory','IO','IOT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(43,'British Virgin Islands','VG','VGB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(44,'Brunei','BN','BRN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(45,'Niue','NU','NIU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(46,'Bolivia','BO','BOL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(47,'Benin','BJ','BEN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(48,'Guinea-Bissau','GW','GNB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(49,'Guinea','GN','GIN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(50,'Latvia','LV','LVA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(51,'Papua New Guinea','PG','PNG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(52,'Peru','PE','PER');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(53,'Antigua and Barbuda','AG','ATG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(54,'Pakistan','PK','PAK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(55,'Philippines','PH','PHL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(56,'Poland','PL','POL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(57,'Åland Islands','AX','ALA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(58,'Zambia','ZM','ZMB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(59,'Estonia','EE','EST');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(60,'Egypt','EG','EGY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(61,'Bermuda','BM','BMU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(62,'South Africa','ZA','ZAF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(63,'Ecuador','EC','ECU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(64,'Italy','IT','ITA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(65,'Angola','AO','AGO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(66,'Ethiopia','ET','ETH');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(67,'Zimbabwe','ZW','ZWE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(68,'Spain','ES','ESP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(69,'Eritrea','ER','ERI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(70,'Montenegro','ME','MNE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(71,'Moldova','MD','MDA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(72,'Madagascar','MG','MDG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(73,'Uruguay','UY','URY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(74,'Monaco','MC','MCO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(75,'Uzbekistan','UZ','UZB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(76,'Myanmar','MM','MMR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(77,'Mali','ML','MLI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(78,'Mongolia','MN','MNG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(79,'Republic of Macedonia','MK','MKD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(80,'Mauritius','MU','MUS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(81,'Malawi','MW','MWI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(82,'Mauritania','MR','MRT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(83,'Uganda','UG','UGA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(84,'Bonaire','BQ','BES');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(85,'Ukraine','UA','UKR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(86,'Mexico','MX','MEX');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(87,'Mozambique','MZ','MOZ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(88,'France','FR','FRA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(89,'Finland','FI','FIN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(90,'Nicaragua','NI','NIC');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(91,'Netherlands','NL','NLD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(92,'Norway','NO','NOR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(93,'Somalia','SO','SOM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(94,'Niger','NE','NER');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(95,'Nigeria','NG','NGA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(96,'New Zealand','NZ','NZL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(97,'Nepal','NP','NPL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(98,'Republic of Kosovo','XK','KOS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(99,'Ivory Coast','CI','CIV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(100,'Switzerland','CH','CHE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(101,'Colombia','CO','COL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(102,'China','CN','CHN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(103,'Cameroon','CM','CMR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(104,'Chile','CL','CHL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(105,'Canada','CA','CAN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(106,'Republic of the Congo','CG','COG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(107,'Central African Republic','CF','CAF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(108,'Democratic Republic of the Congo','CD','COD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(109,'Czech Republic','CZ','CZE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(110,'Morocco','MA','MAR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(111,'Cuba','CU','CUB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(112,'Swaziland','SZ','SWZ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(113,'Syria','SY','SYR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(114,'Kyrgyzstan','KG','KGZ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(115,'Kenya','KE','KEN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(116,'South Sudan','SS','SSD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(117,'Suriname','SR','SUR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(118,'Cambodia','KH','KHM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(119,'Slovakia','SK','SVK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(120,'South Korea','KR','KOR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(121,'Slovenia','SI','SVN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(122,'North Korea','KP','PRK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(123,'Kuwait','KW','KWT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(124,'Senegal','SN','SEN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(125,'Sierra Leone','SL','SLE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(126,'Kazakhstan','KZ','KAZ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(127,'Saudi Arabia','SA','SAU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(128,'Singapore','SG','SGP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(129,'Sweden','SE','SWE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(130,'Sudan','SD','SDN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(131,'Dominican Republic','DO','DOM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(132,'Djibouti','DJ','DJI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(133,'Denmark','DK','DNK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(134,'Germany','DE','DEU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(135,'Yemen','YE','YEM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(136,'Austria','AT','AUT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(137,'Algeria','DZ','DZA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(138,'United States','US','USA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(139,'Tanzania','TZ','TZA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(140,'Laos','LA','LAO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(141,'Taiwan','TW','TWN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(142,'Turkey','TR','TUR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(143,'Sri Lanka','LK','LKA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(144,'Liechtenstein','LI','LIE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(145,'Tunisia','TN','TUN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(146,'Lithuania','LT','LTU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(147,'Luxembourg','LU','LUX');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(148,'Tajikistan','TJ','TJK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(149,'Burkina Faso','BF','BFA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(150,'Jamaica','JM','JAM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(151,'El Salvador','SV','SLV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(152,'Lesotho','LS','LSO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(153,'Thailand','TH','THA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(154,'Togo','TG','TGO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(155,'Chad','TD','TCD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(156,'Bouvet Island','BV','BVT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(157,'Libya','LY','LBY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(158,'United Arab Emirates','AE','ARE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(159,'Venezuela','VE','VEN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(160,'Afghanistan','AF','AFG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(161,'Iraq','IQ','IRQ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(162,'Iceland','IS','ISL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(163,'Iran','IR','IRN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(164,'Armenia','AM','ARM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(165,'Albania','AL','ALB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(166,'Vietnam','VN','VNM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(167,'Argentina','AR','ARG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(168,'Australia','AU','AUS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(169,'Cape Verde','CV','CPV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(170,'Cayman Islands','KY','CYM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(171,'Christmas Island','CX','CXR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(172,'Cocos (Keeling) Islands','CC','CCK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(173,'Comoros','KM','COM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(174,'Cook Islands','CK','COK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(175,'Curaçao','CW','CUW');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(176,'Cyprus','CY','CYP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(177,'Dominica','DM','DMA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(178,'East Timor','TL','TLS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(179,'Falkland Islands','FK','FLK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(180,'Faroe Islands','FO','FRO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(181,'Federated States of Micronesia','FM','FSM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(182,'Fiji','FJ','FJI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(183,'French Polynesia','PF','PYF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(184,'French Southern and Antarctic Lands','TF','ATF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(185,'Gibraltar','GI','GIB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(186,'Grenada','GD','GRD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(187,'Guadeloupe','GP','GLP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(188,'Guam','GU','GUM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(189,'Guernsey','GG','GGY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(190,'Heard Island and McDonald Islands','HM','HMD');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(191,'Hong Kong','HK','HKG');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(192,'Isle of Man','IM','IMN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(193,'Jersey','JE','JEY');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(194,'Kiribati','KI','KIR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(195,'Macau','MO','MAC');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(196,'Maldives','MV','MDV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(197,'Malta','MT','MLT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(198,'Marshall Islands','MH','MHL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(199,'Martinique','MQ','MTQ');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(200,'Mayotte','YT','MYT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(201,'Montserrat','MS','MSR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(202,'Nauru','NR','NRU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(203,'New Caledonia','NC','NCL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(204,'Norfolk Island','NF','NFK');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(205,'Northern Mariana Islands','MP','MNP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(206,'Palau','PW','PLW');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(207,'Palestine','PS','PSE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(208,'Bosnia and Herzegovina','BA','BIH');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(209,'Pitcairn Islands','PN','PCN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(210,'Puerto Rico','PR','PRI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(211,'Qatar','QA','QAT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(212,'Réunion','RE','REU');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(213,'Saint Barthélemy','BL','BLM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(214,'Saint Helena','SH','SHN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(215,'Saint Kitts and Nevis','KN','KNA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(216,'Saint Lucia','LC','LCA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(217,'Saint Martin','MF','MAF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(218,'Saint Pierre and Miquelon','PM','SPM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(219,'Saint Vincent and the Grenadines','VC','VCT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(220,'Samoa','WS','WSM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(221,'San Marino','SM','SMR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(222,'São Tomé and Príncipe','ST','STP');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(223,'Seychelles','SC','SYC');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(224,'Sint Maarten','SX','SXM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(225,'Solomon Islands','SB','SLB');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(226,'South Georgia','GS','SGS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(227,'Svalbard and Jan Mayen','SJ','SJM');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(228,'Tokelau','TK','TKL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(229,'Tonga','TO','TON');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(230,'Trinidad and Tobago','TT','TTO');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(231,'Turks and Caicos Islands','TC','TCA');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(232,'Tuvalu','TV','TUV');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(233,'United States Minor Outlying Islands','UM','UMI');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(234,'Vanuatu','VU','VUT');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(235,'Wallis and Futuna','WF','WLF');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(236,'Western Sahara','EH','ESH');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(237,'Belgium','BE','BEL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(238,'The Bahamas','BS','BHS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(239,'Israel','IL','ISR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(240,'Aruba','AW','ABW');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(241,'India','IN','IND');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(242,'Lebanon','LB','LBN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(243,'Azerbaijan','AZ','AZE');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(244,'Republic of Ireland','IE','IRL');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(245,'Indonesia','ID','IDN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(246,'Panama','PA','PAN');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(247,'Malaysia','MY','MYS');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(248,'US Virgin Islands','VI','VIR');
 insert into gestalt_country_with_name (id, name, iso2code, iso3code) values(249,'Vatican City State','VA','VAT');
