drop table if exists gestalt_subgroup_name; create table gestalt_subgroup_name (id integer, name text);

insert into gestalt_subgroup_name (id, name) values(3126,'Congo (Kinshasa)');
 insert into gestalt_subgroup_name (id, name) values(3127,'Associate');
 insert into gestalt_subgroup_name (id, name) values(3128,'Factional Competition');
 insert into gestalt_subgroup_name (id, name) values(3129,'Executive Parity or Subordination');
 insert into gestalt_subgroup_name (id, name) values(3130,'Island');
 insert into gestalt_subgroup_name (id, name) values(3131,'Western Europe, Iberian');
 insert into gestalt_subgroup_name (id, name) values(3132,'Negative Regime Change');
 insert into gestalt_subgroup_name (id, name) values(3133,'Multiple Identity');
 insert into gestalt_subgroup_name (id, name) values(3134,'Middle East, Mediterranean');
 insert into gestalt_subgroup_name (id, name) values(10,'all');
 insert into gestalt_subgroup_name (id, name) values(3135,'Argentina, Uruguay');
 insert into gestalt_subgroup_name (id, name) values(3136,'Mauritius, Seychelles');
 insert into gestalt_subgroup_name (id, name) values(3137,'New Zealand');
 insert into gestalt_subgroup_name (id, name) values(3138,'European Union');
 insert into gestalt_subgroup_name (id, name) values(3139,'Parliamentary Constitutional Monarchy');
 insert into gestalt_subgroup_name (id, name) values(3140,'B');
 insert into gestalt_subgroup_name (id, name) values(3141,'Latin America');
 insert into gestalt_subgroup_name (id, name) values(3142,'Taipei, China');
 insert into gestalt_subgroup_name (id, name) values(3143,'Chinese Taipei');
 insert into gestalt_subgroup_name (id, name) values(3144,'B-');
 insert into gestalt_subgroup_name (id, name) values(3145,'Azerbaijan');
 insert into gestalt_subgroup_name (id, name) values(3146,'Constitutional Monarchy');
 insert into gestalt_subgroup_name (id, name) values(3147,'Antarctica, Brazil, Chile, United Kingdom, Uruguay');
 insert into gestalt_subgroup_name (id, name) values(3148,'other single currency');
 insert into gestalt_subgroup_name (id, name) values(3149,'Few Risks');
 insert into gestalt_subgroup_name (id, name) values(3150,'Inland-Coastal');
 insert into gestalt_subgroup_name (id, name) values(3151,'Upper middle income');
 insert into gestalt_subgroup_name (id, name) values(3152,'Uninstitutionalized Competition Transition');
 insert into gestalt_subgroup_name (id, name) values(3153,'MENA');
 insert into gestalt_subgroup_name (id, name) values(3154,'Turkey');
 insert into gestalt_subgroup_name (id, name) values(3155,'A');
 insert into gestalt_subgroup_name (id, name) values(3156,'Oceania');
 insert into gestalt_subgroup_name (id, name) values(3157,'Caribbean');
 insert into gestalt_subgroup_name (id, name) values(3158,'AA-');
 insert into gestalt_subgroup_name (id, name) values(3159,'High income');
 insert into gestalt_subgroup_name (id, name) values(3160,'Lesser Antilles');
 insert into gestalt_subgroup_name (id, name) values(3161,'Antarctica, Argentina, Bolivia');
 insert into gestalt_subgroup_name (id, name) values(3162,'None');
 insert into gestalt_subgroup_name (id, name) values(3163,'France');
 insert into gestalt_subgroup_name (id, name) values(3164,'IMF EM and Dev');
 insert into gestalt_subgroup_name (id, name) values(3165,'Rwanda');
 insert into gestalt_subgroup_name (id, name) values(3166,'Northern Europe, Scandanavia');
 insert into gestalt_subgroup_name (id, name) values(3167,'bands');
 insert into gestalt_subgroup_name (id, name) values(3168,'Self-Selection');
 insert into gestalt_subgroup_name (id, name) values(3169,'B+');
 insert into gestalt_subgroup_name (id, name) values(3170,'Norway');
 insert into gestalt_subgroup_name (id, name) values(3171,'Central Africa');
 insert into gestalt_subgroup_name (id, name) values(3172,'Treaty System');
 insert into gestalt_subgroup_name (id, name) values(3173,'Arabian Peninsula');
 insert into gestalt_subgroup_name (id, name) values(3174,'Libya');
 insert into gestalt_subgroup_name (id, name) values(3175,'Factional');
 insert into gestalt_subgroup_name (id, name) values(3176,'OMR');
 insert into gestalt_subgroup_name (id, name) values(3177,'Lower middle income');
 insert into gestalt_subgroup_name (id, name) values(3178,'BB');
 insert into gestalt_subgroup_name (id, name) values(3179,'Antarctica, Indonesia');
 insert into gestalt_subgroup_name (id, name) values(3180,'Dual Executive-Election');
 insert into gestalt_subgroup_name (id, name) values(3181,'China');
 insert into gestalt_subgroup_name (id, name) values(3182,'Honduras, Nicaragua, Jamaica, United States, Venezuela');
 insert into gestalt_subgroup_name (id, name) values(3183,'Armenia');
 insert into gestalt_subgroup_name (id, name) values(3184,'Authoritarian Presidential Republic');
 insert into gestalt_subgroup_name (id, name) values(3185,'peg');
 insert into gestalt_subgroup_name (id, name) values(3186,'Caucuses');
 insert into gestalt_subgroup_name (id, name) values(3187,'Former');
 insert into gestalt_subgroup_name (id, name) values(3188,'Low income');
 insert into gestalt_subgroup_name (id, name) values(3189,'Angola, Uganda, Zambia');
 insert into gestalt_subgroup_name (id, name) values(3190,'Chile, Peru');
 insert into gestalt_subgroup_name (id, name) values(3191,'Communist State');
 insert into gestalt_subgroup_name (id, name) values(3192,'Under Foreign Authority');
 insert into gestalt_subgroup_name (id, name) values(3193,'West Africa');
 insert into gestalt_subgroup_name (id, name) values(3194,'Bosnia and Herzegovina, Slovenia');
 insert into gestalt_subgroup_name (id, name) values(3195,'Presidential Republic');
 insert into gestalt_subgroup_name (id, name) values(3196,'Sectarian');
 insert into gestalt_subgroup_name (id, name) values(3197,'crawl-like arrangement');
 insert into gestalt_subgroup_name (id, name) values(3198,'North America');
 insert into gestalt_subgroup_name (id, name) values(3199,'Dual/Transitional');
 insert into gestalt_subgroup_name (id, name) values(3200,'Not Self Governing');
 insert into gestalt_subgroup_name (id, name) values(3201,'EZ');
 insert into gestalt_subgroup_name (id, name) values(3202,'EU');
 insert into gestalt_subgroup_name (id, name) values(3203,'Presidential Islamic Republic');
 insert into gestalt_subgroup_name (id, name) values(3204,'conventional peg');
 insert into gestalt_subgroup_name (id, name) values(3205,'no separate currency');
 insert into gestalt_subgroup_name (id, name) values(3206,'United States');
 insert into gestalt_subgroup_name (id, name) values(3207,'Selection');
 insert into gestalt_subgroup_name (id, name) values(3208,'East Africa');
 insert into gestalt_subgroup_name (id, name) values(3209,'East Asia');
 insert into gestalt_subgroup_name (id, name) values(3210,'Tokelau');
 insert into gestalt_subgroup_name (id, name) values(3211,'EU-OMR');
 insert into gestalt_subgroup_name (id, name) values(3212,'Former Soviet Union');
 insert into gestalt_subgroup_name (id, name) values(3213,'Parliamentary Republic');
 insert into gestalt_subgroup_name (id, name) values(3214,'Malaysia');
 insert into gestalt_subgroup_name (id, name) values(3215,'South America');
 insert into gestalt_subgroup_name (id, name) values(3216,'Regulated');
 insert into gestalt_subgroup_name (id, name) values(3217,'Coastal');
 insert into gestalt_subgroup_name (id, name) values(3218,'Associate Member');
 insert into gestalt_subgroup_name (id, name) values(3219,'Japan');
 insert into gestalt_subgroup_name (id, name) values(3220,'Antarctic');
 insert into gestalt_subgroup_name (id, name) values(3221,'No Overt');
 insert into gestalt_subgroup_name (id, name) values(3222,'Investment');
 insert into gestalt_subgroup_name (id, name) values(3223,'Enhanced Engagement');
 insert into gestalt_subgroup_name (id, name) values(3224,'Netherlands');
 insert into gestalt_subgroup_name (id, name) values(3225,'In Transition');
 insert into gestalt_subgroup_name (id, name) values(3226,'No');
 insert into gestalt_subgroup_name (id, name) values(3227,'net importer');
 insert into gestalt_subgroup_name (id, name) values(3228,'Junk');
 insert into gestalt_subgroup_name (id, name) values(3229,'Asia');
 insert into gestalt_subgroup_name (id, name) values(3230,'Member');
 insert into gestalt_subgroup_name (id, name) values(3231,'Former Yugoslavia');
 insert into gestalt_subgroup_name (id, name) values(3232,'Formally Excluded');
 insert into gestalt_subgroup_name (id, name) values(3233,'FSU');
 insert into gestalt_subgroup_name (id, name) values(3234,'Closed');
 insert into gestalt_subgroup_name (id, name) values(3235,'Central Asia');
 insert into gestalt_subgroup_name (id, name) values(3236,'Parliamentary Democracy under Constitutional Monarchy');
 insert into gestalt_subgroup_name (id, name) values(3237,'Major Limitation');
 insert into gestalt_subgroup_name (id, name) values(3238,'Moderate');
 insert into gestalt_subgroup_name (id, name) values(3239,'Ascription');
 insert into gestalt_subgroup_name (id, name) values(3240,'Pending');
 insert into gestalt_subgroup_name (id, name) values(3241,'Europe');
 insert into gestalt_subgroup_name (id, name) values(3242,'BB-');
 insert into gestalt_subgroup_name (id, name) values(3243,'Australia');
 insert into gestalt_subgroup_name (id, name) values(3244,'BB+');
 insert into gestalt_subgroup_name (id, name) values(3245,'Participating Member');
 insert into gestalt_subgroup_name (id, name) values(3246,'working');
 insert into gestalt_subgroup_name (id, name) values(3247,'Slight');
 insert into gestalt_subgroup_name (id, name) values(3248,'Benin, Niger, Mali');
 insert into gestalt_subgroup_name (id, name) values(3249,'currency board');
 insert into gestalt_subgroup_name (id, name) values(3250,'Federal Republic');
 insert into gestalt_subgroup_name (id, name) values(3251,'State Failure');
 insert into gestalt_subgroup_name (id, name) values(3252,'Partial autocracy');
 insert into gestalt_subgroup_name (id, name) values(3253,'Major Democratic Transition');
 insert into gestalt_subgroup_name (id, name) values(3254,'NS');
 insert into gestalt_subgroup_name (id, name) values(3255,'Burkina Faso, Niger, Nigeria');
 insert into gestalt_subgroup_name (id, name) values(3256,'East Asia ex. China');
 insert into gestalt_subgroup_name (id, name) values(3257,'Most Risk');
 insert into gestalt_subgroup_name (id, name) values(3258,'EU-OCT');
 insert into gestalt_subgroup_name (id, name) values(3259,'yes');
 insert into gestalt_subgroup_name (id, name) values(3260,'Absolute Monarchy');
 insert into gestalt_subgroup_name (id, name) values(3261,'BBB+');
 insert into gestalt_subgroup_name (id, name) values(3262,'Designation');
 insert into gestalt_subgroup_name (id, name) values(3263,'CC');
 insert into gestalt_subgroup_name (id, name) values(3264,'Denmark');
 insert into gestalt_subgroup_name (id, name) values(3265,'Transition');
 insert into gestalt_subgroup_name (id, name) values(3266,'other managed');
 insert into gestalt_subgroup_name (id, name) values(3267,'Dual Executive-Designation');
 insert into gestalt_subgroup_name (id, name) values(3268,'Adverse Regime Transition');
 insert into gestalt_subgroup_name (id, name) values(3269,'Morocco');
 insert into gestalt_subgroup_name (id, name) values(3270,'Full autocracy');
 insert into gestalt_subgroup_name (id, name) values(3271,'Federation of Monarchies');
 insert into gestalt_subgroup_name (id, name) values(3272,'Non-Member');
 insert into gestalt_subgroup_name (id, name) values(3273,'Factional/Restricted Competition');
 insert into gestalt_subgroup_name (id, name) values(3274,'Thailand, Vietnam');
 insert into gestalt_subgroup_name (id, name) values(3275,'Transitional or Restricted Election');
 insert into gestalt_subgroup_name (id, name) values(3276,'Observer');
 insert into gestalt_subgroup_name (id, name) values(3277,'other managed arrangement');
 insert into gestalt_subgroup_name (id, name) values(3278,'BBB-');
 insert into gestalt_subgroup_name (id, name) values(3279,'Africa');
 insert into gestalt_subgroup_name (id, name) values(3280,'Dual Executive: Ascription+Election');
 insert into gestalt_subgroup_name (id, name) values(3281,'composite');
 insert into gestalt_subgroup_name (id, name) values(3282,'Eastern Europe');
 insert into gestalt_subgroup_name (id, name) values(3283,'Other');
 insert into gestalt_subgroup_name (id, name) values(3284,'Sub-Sahara Africa');
 insert into gestalt_subgroup_name (id, name) values(3285,'East and Southeast Asia');
 insert into gestalt_subgroup_name (id, name) values(3286,'IMF advanced');
 insert into gestalt_subgroup_name (id, name) values(3287,'Unlimited Authority');
 insert into gestalt_subgroup_name (id, name) values(3288,'Former Iron Curtain');
 insert into gestalt_subgroup_name (id, name) values(3289,'Nicaragua');
 insert into gestalt_subgroup_name (id, name) values(3290,'Foreign Authority Interruption');
 insert into gestalt_subgroup_name (id, name) values(3291,'Parliamentary');
 insert into gestalt_subgroup_name (id, name) values(3292,'free floating');
 insert into gestalt_subgroup_name (id, name) values(3293,'AAA');
 insert into gestalt_subgroup_name (id, name) values(3294,'Designational/Transitional');
 insert into gestalt_subgroup_name (id, name) values(3295,'Tentative');
 insert into gestalt_subgroup_name (id, name) values(3296,'China, Malaysia, Vietnam');
 insert into gestalt_subgroup_name (id, name) values(3297,'Serbia');
 insert into gestalt_subgroup_name (id, name) values(3298,'Theocratic Republic');
 insert into gestalt_subgroup_name (id, name) values(3299,'Dialogue Member');
 insert into gestalt_subgroup_name (id, name) values(3300,'Peaceful Factional Competition Transition');
 insert into gestalt_subgroup_name (id, name) values(3301,'Unregulated');
 insert into gestalt_subgroup_name (id, name) values(3302,'Guatemala, Mexico');
 insert into gestalt_subgroup_name (id, name) values(3303,'AA+');
 insert into gestalt_subgroup_name (id, name) values(3304,'Suspended');
 insert into gestalt_subgroup_name (id, name) values(3305,'ERM');
 insert into gestalt_subgroup_name (id, name) values(3306,'net exporter');
 insert into gestalt_subgroup_name (id, name) values(3307,'Central Europe');
 insert into gestalt_subgroup_name (id, name) values(3308,'Slight Limitation');
 insert into gestalt_subgroup_name (id, name) values(3309,'floating');
 insert into gestalt_subgroup_name (id, name) values(3310,'Significant Risk');
 insert into gestalt_subgroup_name (id, name) values(3311,'Unregulated/Transitional');
 insert into gestalt_subgroup_name (id, name) values(3312,'United Kingdom');
 insert into gestalt_subgroup_name (id, name) values(3313,'Israel');
 insert into gestalt_subgroup_name (id, name) values(3314,'Federal Parliamentary Republic');
 insert into gestalt_subgroup_name (id, name) values(3084,'Canada');
 insert into gestalt_subgroup_name (id, name) values(3085,'1');
 insert into gestalt_subgroup_name (id, name) values(3086,'2');
 insert into gestalt_subgroup_name (id, name) values(3087,'3');
 insert into gestalt_subgroup_name (id, name) values(3088,'4');
 insert into gestalt_subgroup_name (id, name) values(3089,'5');
 insert into gestalt_subgroup_name (id, name) values(3090,'Candidate');
 insert into gestalt_subgroup_name (id, name) values(3091,'Restricted');
 insert into gestalt_subgroup_name (id, name) values(3092,'Serious');
 insert into gestalt_subgroup_name (id, name) values(3093,'dollar');
 insert into gestalt_subgroup_name (id, name) values(3094,'Parliamentary Democracy');
 insert into gestalt_subgroup_name (id, name) values(3095,'Interruption Period');
 insert into gestalt_subgroup_name (id, name) values(3096,'CCC');
 insert into gestalt_subgroup_name (id, name) values(3097,'Confident');
 insert into gestalt_subgroup_name (id, name) values(3098,'Middle East');
 insert into gestalt_subgroup_name (id, name) values(3099,'Substantial Limitation');
 insert into gestalt_subgroup_name (id, name) values(3100,'Dialogue Partner');
 insert into gestalt_subgroup_name (id, name) values(3101,'Central America and Caribbean');
 insert into gestalt_subgroup_name (id, name) values(3102,'South Asia');
 insert into gestalt_subgroup_name (id, name) values(3103,'Argentina');
 insert into gestalt_subgroup_name (id, name) values(3104,'Presidential Democracy');
 insert into gestalt_subgroup_name (id, name) values(3105,'Repressed');
 insert into gestalt_subgroup_name (id, name) values(3106,'Non-EU28');
 insert into gestalt_subgroup_name (id, name) values(3107,'0');
 insert into gestalt_subgroup_name (id, name) values(3108,'EU Dialog Member');
 insert into gestalt_subgroup_name (id, name) values(3109,'6');
 insert into gestalt_subgroup_name (id, name) values(3110,'Restrictive Factional Competition Transition');
 insert into gestalt_subgroup_name (id, name) values(3111,'Not Applicable');
 insert into gestalt_subgroup_name (id, name) values(3112,'Repressed Competition');
 insert into gestalt_subgroup_name (id, name) values(3113,'Semi-Presidential Federation');
 insert into gestalt_subgroup_name (id, name) values(3114,'Eastern Europe, Balkan');
 insert into gestalt_subgroup_name (id, name) values(3115,'Some Risk');
 insert into gestalt_subgroup_name (id, name) values(3116,'Denmark, United States');
 insert into gestalt_subgroup_name (id, name) values(3117,'Sub-Saharan Africa');
 insert into gestalt_subgroup_name (id, name) values(3118,'Recent Regime Change');
 insert into gestalt_subgroup_name (id, name) values(3119,'Commonwealth Realm');
 insert into gestalt_subgroup_name (id, name) values(3120,'Australia-Oceania');
 insert into gestalt_subgroup_name (id, name) values(3121,'Suppressed');
 insert into gestalt_subgroup_name (id, name) values(3122,'North Africa');
 insert into gestalt_subgroup_name (id, name) values(3123,'Spain');
 insert into gestalt_subgroup_name (id, name) values(3124,'Federal Parliamentary Democracy under Constitutional Monarchy');
 insert into gestalt_subgroup_name (id, name) values(3125,'Uninstitutionalized Competition');
 insert into gestalt_subgroup_name (id, name) values(3315,'Bhutan, Brunei, Hong Kong, India, Japan, Malaysia, North Korea, Pakistan, Philippines, Taiwan, Tajikistan, Vietnam');
 insert into gestalt_subgroup_name (id, name) values(3316,'Federal Presidential Republic');
 insert into gestalt_subgroup_name (id, name) values(3317,'Interregnum Period');
 insert into gestalt_subgroup_name (id, name) values(3318,'EU Member');
 insert into gestalt_subgroup_name (id, name) values(3319,'A-');
 insert into gestalt_subgroup_name (id, name) values(3320,'OCT');
 insert into gestalt_subgroup_name (id, name) values(3321,'Partial democracy');
 insert into gestalt_subgroup_name (id, name) values(3322,'Greater Antilles');
 insert into gestalt_subgroup_name (id, name) values(3323,'Slight to Moderate Limitation');
 insert into gestalt_subgroup_name (id, name) values(3324,'Non-member');
 insert into gestalt_subgroup_name (id, name) values(3325,'no peg');
 insert into gestalt_subgroup_name (id, name) values(3326,'stabilized arrangement');
 insert into gestalt_subgroup_name (id, name) values(3327,'Dual Executive: Ascription+Designation');
 insert into gestalt_subgroup_name (id, name) values(3328,'Positive Regime Change');
 insert into gestalt_subgroup_name (id, name) values(3329,'crawling peg');
 insert into gestalt_subgroup_name (id, name) values(3330,'AA');
 insert into gestalt_subgroup_name (id, name) values(3331,'Interregnal');
 insert into gestalt_subgroup_name (id, name) values(3332,'Transitional');
 insert into gestalt_subgroup_name (id, name) values(3333,'Partial democracy/factionalism');
 insert into gestalt_subgroup_name (id, name) values(3334,'France, Madagascar, Mayotte');
 insert into gestalt_subgroup_name (id, name) values(3335,'no subgroup');
 insert into gestalt_subgroup_name (id, name) values(3336,'Gradual Transition from Self-Selection');
 insert into gestalt_subgroup_name (id, name) values(3337,'Authority Collapse');
 insert into gestalt_subgroup_name (id, name) values(3338,'BBB');
 insert into gestalt_subgroup_name (id, name) values(3339,'Southern Africa');
 insert into gestalt_subgroup_name (id, name) values(3340,'Restricted Competition');
 insert into gestalt_subgroup_name (id, name) values(3341,'Authoritarian-Guided Competition');
 insert into gestalt_subgroup_name (id, name) values(3342,'Argentina, Australia, Chile, France, New Zealand, Norway, United Kingdom');
 insert into gestalt_subgroup_name (id, name) values(3343,'Full democracy');
 insert into gestalt_subgroup_name (id, name) values(3344,'euro');
 insert into gestalt_subgroup_name (id, name) values(3345,'Competitive Election');
 insert into gestalt_subgroup_name (id, name) values(3346,'SDR');
 insert into gestalt_subgroup_name (id, name) values(3347,'Equatorial Guinea');
 insert into gestalt_subgroup_name (id, name) values(3348,'Central America');
 insert into gestalt_subgroup_name (id, name) values(3349,'Presidential Limited Democracy');
 insert into gestalt_subgroup_name (id, name) values(3350,'Institutionalized Open Competition');
 insert into gestalt_subgroup_name (id, name) values(3351,'no');
 insert into gestalt_subgroup_name (id, name) values(3352,'Southeast Asia');
 insert into gestalt_subgroup_name (id, name) values(3353,'Competitive');
 insert into gestalt_subgroup_name (id, name) values(3354,'Indian Ocean');
 insert into gestalt_subgroup_name (id, name) values(3355,'Inland');
 insert into gestalt_subgroup_name (id, name) values(3356,'Antarctica');
 insert into gestalt_subgroup_name (id, name) values(3357,'Russia and Eastern Europe');
 insert into gestalt_subgroup_name (id, name) values(3358,'Election');
 insert into gestalt_subgroup_name (id, name) values(3359,'Tenuous');
 insert into gestalt_subgroup_name (id, name) values(3360,'A+');
 insert into gestalt_subgroup_name (id, name) values(3361,'basket');
 insert into gestalt_subgroup_name (id, name) values(3362,'Open');
 insert into gestalt_subgroup_name (id, name) values(3363,'Western Europe');
 insert into gestalt_subgroup_name (id, name) values(3364,'Semi-Presidential Republic');
 insert into gestalt_subgroup_name (id, name) values(3365,'Moderate Limitation');
