drop table if exists gestalt_workspace_name; create table gestalt_workspace_name (id serial primary key,name text);
 insert into gestalt_workspace_name (name) values ('Gestalt');
 insert into gestalt_workspace_name (name) values ('Economics');
 insert into gestalt_workspace_name (name) values ('SDN Anomolies');
select * from gestalt_workspace_name;
drop table if exists gestalt_workspace; create table gestalt_workspace (id serial primary key, workspace_name_id integer,persona_id integer,url_name text,is_default boolean);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (1,1,'gestalt',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (1,4,'gestalt',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (1,6,'gestalt',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (2,1,'economics',false);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (2,2,'economics',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (2,6,'economics',false);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (3,3,'software-defined-networking',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (3,5,'software-defined-networking',true);
 insert into gestalt_workspace (workspace_name_id,persona_id,url_name,is_default) values (3,6,'software-defined-networking',false);
select * from gestalt_workspace where persona_id = 5;
drop table if exists gestalt_panel; create table gestalt_panel (id serial primary key,name text,url_name text);
 insert into gestalt_panel (name,url_name) values ('form','visual-form');
 insert into gestalt_panel (name,url_name) values ('tools','visual-tool');
 insert into gestalt_panel (name,url_name) values ('contagion','contagion');
 insert into gestalt_panel (name,url_name) values ('classification','classification');
 insert into gestalt_panel (name,url_name) values ('activity','activity');
select * from gestalt_panel;
drop table if exists gestalt_workspace_panel; create table gestalt_workspace_panel (id serial primary key,workspace_id integer,panel_id integer,is_default boolean);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (1,1,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (2,1,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (3,1,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (1,2,false);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (2,2,false);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (3,2,false);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (4,3,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (5,3,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (6,3,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (7,4,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (8,4,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (9,4,true);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (7,5,false);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (8,5,false);
 insert into gestalt_workspace_panel (workspace_id,panel_id,is_default) values (9,5,false);
select * from gestalt_workspace_panel;
drop table if exists gestalt_story; create table gestalt_story (id serial primary key,name text,url_name text,vis_id integer, action_id integer, story_order integer, intro text);
 insert into gestalt_story (story_order,name,url_name, vis_id, intro) values (1,'What tool to use for which data visualization task','visualization-standard',15, 'The proliferation of data visualization tools makes it difficult to know what tool is best suited for what point of the overall visualization workflow. We''ve experimented with many of the available technologies in various environments with varied visualization goals. This is our collection of what we found.');
 insert into gestalt_story (story_order,name,url_name, vis_id, intro) values (1,'What visual form best communicates your dataset','tbd',3, 'Choosing the right form for what kind of visual data story you''re trying to craft is vital to comprehension. We''ve experiemented with several different visual forms for different meanings in visual data stories and these are the results.');
 insert into gestalt_story (story_order,name,url_name, vis_id, intro) values (2,'Global dependencies and connections in econominc networks.','economic-networks',16,'Global financial systems are interconnected and a series of dependencies and influence. Notice how these groups do something interesting, will put lorem ipsum here if I can''t get info from econ team.');
 insert into gestalt_story (story_order,name,url_name, vis_id) values (1,'tbd','tbd',3);
 insert into gestalt_story (story_order,name,url_name, vis_id, intro) values (1,'What is economic contagion?','contagion-background',16,'In economics and finance, a contagion can be explained as a situation where a shock in a particular economy or region spreads out and affects others by way of, say, price movements. Description: The contagion effect explains the possibility of spread of economic crisis or boom across countries or regions.');
 insert into gestalt_story (story_order,name,url_name, intro) values (3,'A scenario for economic contagion to spread.','contagion-spread', 'In this scenario a shock is introduced to low income oil exporters and note the spread and quarentine boundaries of the crisis.');
 insert into gestalt_story (story_order, vis_id, name,url_name, intro) values (1,11,'Classifying anomolies and stuff.','anomolies', 'Some kind of intro/description? More text here to just fill the space assuming there is enough to say about this story.');
  insert into gestalt_story (story_order, vis_id, name,url_name, intro) values (1,14,'Here''s some activity.','networks', 'Some kind of intro/description? More text here to just fill the space assuming there is enough to say about this story.');
select * from gestalt_story;
drop table if exists gestalt_persona_panel_story; create table gestalt_persona_panel_story (id serial primary key,persona_id integer,panel_id integer,story_id integer);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (1,1,2);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (4,1,2);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,1,2);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (1,2,1);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (4,2,1);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,2,1);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (1,3,3);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (2,3,3);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,3,3);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (1,3,5);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,3,5);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (1,3,6);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (2,3,6);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,3,6);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (3,4,7);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (5,4,7);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,4,7);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (3,5,8);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (5,5,8);
 insert into gestalt_persona_panel_story (persona_id,panel_id,story_id) values (6,5,8);
select * from gestalt_persona_panel_story;