drop table if exists gestalt_geography_name; create table gestalt_geography_name (id integer, name text);

insert into gestalt_geography_name (id, name) values(1,'Bangladesh');
 insert into gestalt_geography_name (id, name) values(2,'Bulgaria');
 insert into gestalt_geography_name (id, name) values(3,'Namibia');
 insert into gestalt_geography_name (id, name) values(4,'Barbados');
 insert into gestalt_geography_name (id, name) values(5,'Japan');
 insert into gestalt_geography_name (id, name) values(6,'Burundi');
 insert into gestalt_geography_name (id, name) values(7,'Bhutan');
 insert into gestalt_geography_name (id, name) values(8,'Botswana');
 insert into gestalt_geography_name (id, name) values(9,'Brazil');
 insert into gestalt_geography_name (id, name) values(10,'Belarus');
 insert into gestalt_geography_name (id, name) values(11,'Belize');
 insert into gestalt_geography_name (id, name) values(12,'Russia');
 insert into gestalt_geography_name (id, name) values(13,'Rwanda');
 insert into gestalt_geography_name (id, name) values(14,'Serbia');
 insert into gestalt_geography_name (id, name) values(15,'Turkmenistan');
 insert into gestalt_geography_name (id, name) values(16,'Liberia');
 insert into gestalt_geography_name (id, name) values(17,'Romania');
 insert into gestalt_geography_name (id, name) values(18,'Guatemala');
 insert into gestalt_geography_name (id, name) values(19,'Greece');
 insert into gestalt_geography_name (id, name) values(20,'Equatorial Guinea');
 insert into gestalt_geography_name (id, name) values(21,'American Samoa');
 insert into gestalt_geography_name (id, name) values(22,'Andorra');
 insert into gestalt_geography_name (id, name) values(23,'Anguilla');
 insert into gestalt_geography_name (id, name) values(24,'Bahrain');
 insert into gestalt_geography_name (id, name) values(25,'Guyana');
 insert into gestalt_geography_name (id, name) values(26,'French Guiana');
 insert into gestalt_geography_name (id, name) values(27,'Georgia');
 insert into gestalt_geography_name (id, name) values(28,'United Kingdom');
 insert into gestalt_geography_name (id, name) values(29,'Gabon');
 insert into gestalt_geography_name (id, name) values(30,'The Gambia');
 insert into gestalt_geography_name (id, name) values(31,'Greenland');
 insert into gestalt_geography_name (id, name) values(32,'Ghana');
 insert into gestalt_geography_name (id, name) values(33,'Oman');
 insert into gestalt_geography_name (id, name) values(34,'Jordan');
 insert into gestalt_geography_name (id, name) values(35,'Croatia');
 insert into gestalt_geography_name (id, name) values(36,'Haiti');
 insert into gestalt_geography_name (id, name) values(37,'Hungary');
 insert into gestalt_geography_name (id, name) values(38,'Honduras');
 insert into gestalt_geography_name (id, name) values(39,'Costa Rica');
 insert into gestalt_geography_name (id, name) values(40,'Portugal');
 insert into gestalt_geography_name (id, name) values(41,'Paraguay');
 insert into gestalt_geography_name (id, name) values(42,'British Indian Ocean Territory');
 insert into gestalt_geography_name (id, name) values(43,'British Virgin Islands');
 insert into gestalt_geography_name (id, name) values(44,'Brunei');
 insert into gestalt_geography_name (id, name) values(45,'Niue');
 insert into gestalt_geography_name (id, name) values(46,'Bolivia');
 insert into gestalt_geography_name (id, name) values(47,'Benin');
 insert into gestalt_geography_name (id, name) values(48,'Guinea-Bissau');
 insert into gestalt_geography_name (id, name) values(49,'Guinea');
 insert into gestalt_geography_name (id, name) values(50,'Latvia');
 insert into gestalt_geography_name (id, name) values(51,'Papua New Guinea');
 insert into gestalt_geography_name (id, name) values(52,'Peru');
 insert into gestalt_geography_name (id, name) values(53,'Antigua and Barbuda');
 insert into gestalt_geography_name (id, name) values(54,'Pakistan');
 insert into gestalt_geography_name (id, name) values(55,'Philippines');
 insert into gestalt_geography_name (id, name) values(56,'Poland');
 insert into gestalt_geography_name (id, name) values(57,'Åland Islands');
 insert into gestalt_geography_name (id, name) values(58,'Zambia');
 insert into gestalt_geography_name (id, name) values(59,'Estonia');
 insert into gestalt_geography_name (id, name) values(60,'Egypt');
 insert into gestalt_geography_name (id, name) values(61,'Bermuda');
 insert into gestalt_geography_name (id, name) values(62,'South Africa');
 insert into gestalt_geography_name (id, name) values(63,'Ecuador');
 insert into gestalt_geography_name (id, name) values(64,'Italy');
 insert into gestalt_geography_name (id, name) values(65,'Angola');
 insert into gestalt_geography_name (id, name) values(66,'Ethiopia');
 insert into gestalt_geography_name (id, name) values(67,'Zimbabwe');
 insert into gestalt_geography_name (id, name) values(68,'Spain');
 insert into gestalt_geography_name (id, name) values(69,'Eritrea');
 insert into gestalt_geography_name (id, name) values(70,'Montenegro');
 insert into gestalt_geography_name (id, name) values(71,'Moldova');
 insert into gestalt_geography_name (id, name) values(72,'Madagascar');
 insert into gestalt_geography_name (id, name) values(73,'Uruguay');
 insert into gestalt_geography_name (id, name) values(74,'Monaco');
 insert into gestalt_geography_name (id, name) values(75,'Uzbekistan');
 insert into gestalt_geography_name (id, name) values(76,'Myanmar');
 insert into gestalt_geography_name (id, name) values(77,'Mali');
 insert into gestalt_geography_name (id, name) values(78,'Mongolia');
 insert into gestalt_geography_name (id, name) values(79,'Republic of Macedonia');
 insert into gestalt_geography_name (id, name) values(80,'Mauritius');
 insert into gestalt_geography_name (id, name) values(81,'Malawi');
 insert into gestalt_geography_name (id, name) values(82,'Mauritania');
 insert into gestalt_geography_name (id, name) values(83,'Uganda');
 insert into gestalt_geography_name (id, name) values(84,'Bonaire');
 insert into gestalt_geography_name (id, name) values(85,'Ukraine');
 insert into gestalt_geography_name (id, name) values(86,'Mexico');
 insert into gestalt_geography_name (id, name) values(87,'Mozambique');
 insert into gestalt_geography_name (id, name) values(88,'France');
 insert into gestalt_geography_name (id, name) values(89,'Finland');
 insert into gestalt_geography_name (id, name) values(90,'Nicaragua');
 insert into gestalt_geography_name (id, name) values(91,'Netherlands');
 insert into gestalt_geography_name (id, name) values(92,'Norway');
 insert into gestalt_geography_name (id, name) values(93,'Somalia');
 insert into gestalt_geography_name (id, name) values(94,'Niger');
 insert into gestalt_geography_name (id, name) values(95,'Nigeria');
 insert into gestalt_geography_name (id, name) values(96,'New Zealand');
 insert into gestalt_geography_name (id, name) values(97,'Nepal');
 insert into gestalt_geography_name (id, name) values(98,'Republic of Kosovo');
 insert into gestalt_geography_name (id, name) values(99,'Ivory Coast');
 insert into gestalt_geography_name (id, name) values(100,'Switzerland');
 insert into gestalt_geography_name (id, name) values(101,'Colombia');
 insert into gestalt_geography_name (id, name) values(102,'China');
 insert into gestalt_geography_name (id, name) values(103,'Cameroon');
 insert into gestalt_geography_name (id, name) values(104,'Chile');
 insert into gestalt_geography_name (id, name) values(105,'Canada');
 insert into gestalt_geography_name (id, name) values(106,'Republic of the Congo');
 insert into gestalt_geography_name (id, name) values(107,'Central African Republic');
 insert into gestalt_geography_name (id, name) values(108,'Democratic Republic of the Congo');
 insert into gestalt_geography_name (id, name) values(109,'Czech Republic');
 insert into gestalt_geography_name (id, name) values(110,'Morocco');
 insert into gestalt_geography_name (id, name) values(111,'Cuba');
 insert into gestalt_geography_name (id, name) values(112,'Swaziland');
 insert into gestalt_geography_name (id, name) values(113,'Syria');
 insert into gestalt_geography_name (id, name) values(114,'Kyrgyzstan');
 insert into gestalt_geography_name (id, name) values(115,'Kenya');
 insert into gestalt_geography_name (id, name) values(116,'South Sudan');
 insert into gestalt_geography_name (id, name) values(117,'Suriname');
 insert into gestalt_geography_name (id, name) values(118,'Cambodia');
 insert into gestalt_geography_name (id, name) values(119,'Slovakia');
 insert into gestalt_geography_name (id, name) values(120,'South Korea');
 insert into gestalt_geography_name (id, name) values(121,'Slovenia');
 insert into gestalt_geography_name (id, name) values(122,'North Korea');
 insert into gestalt_geography_name (id, name) values(123,'Kuwait');
 insert into gestalt_geography_name (id, name) values(124,'Senegal');
 insert into gestalt_geography_name (id, name) values(125,'Sierra Leone');
 insert into gestalt_geography_name (id, name) values(126,'Kazakhstan');
 insert into gestalt_geography_name (id, name) values(127,'Saudi Arabia');
 insert into gestalt_geography_name (id, name) values(128,'Singapore');
 insert into gestalt_geography_name (id, name) values(129,'Sweden');
 insert into gestalt_geography_name (id, name) values(130,'Sudan');
 insert into gestalt_geography_name (id, name) values(131,'Dominican Republic');
 insert into gestalt_geography_name (id, name) values(132,'Djibouti');
 insert into gestalt_geography_name (id, name) values(133,'Denmark');
 insert into gestalt_geography_name (id, name) values(134,'Germany');
 insert into gestalt_geography_name (id, name) values(135,'Yemen');
 insert into gestalt_geography_name (id, name) values(136,'Austria');
 insert into gestalt_geography_name (id, name) values(137,'Algeria');
 insert into gestalt_geography_name (id, name) values(138,'United States');
 insert into gestalt_geography_name (id, name) values(139,'Tanzania');
 insert into gestalt_geography_name (id, name) values(140,'Laos');
 insert into gestalt_geography_name (id, name) values(141,'Taiwan');
 insert into gestalt_geography_name (id, name) values(142,'Turkey');
 insert into gestalt_geography_name (id, name) values(143,'Sri Lanka');
 insert into gestalt_geography_name (id, name) values(144,'Liechtenstein');
 insert into gestalt_geography_name (id, name) values(145,'Tunisia');
 insert into gestalt_geography_name (id, name) values(146,'Lithuania');
 insert into gestalt_geography_name (id, name) values(147,'Luxembourg');
 insert into gestalt_geography_name (id, name) values(148,'Tajikistan');
 insert into gestalt_geography_name (id, name) values(149,'Burkina Faso');
 insert into gestalt_geography_name (id, name) values(150,'Jamaica');
 insert into gestalt_geography_name (id, name) values(151,'El Salvador');
 insert into gestalt_geography_name (id, name) values(152,'Lesotho');
 insert into gestalt_geography_name (id, name) values(153,'Thailand');
 insert into gestalt_geography_name (id, name) values(154,'Togo');
 insert into gestalt_geography_name (id, name) values(155,'Chad');
 insert into gestalt_geography_name (id, name) values(156,'Bouvet Island');
 insert into gestalt_geography_name (id, name) values(157,'Libya');
 insert into gestalt_geography_name (id, name) values(158,'United Arab Emirates');
 insert into gestalt_geography_name (id, name) values(159,'Venezuela');
 insert into gestalt_geography_name (id, name) values(160,'Afghanistan');
 insert into gestalt_geography_name (id, name) values(161,'Iraq');
 insert into gestalt_geography_name (id, name) values(162,'Iceland');
 insert into gestalt_geography_name (id, name) values(163,'Iran');
 insert into gestalt_geography_name (id, name) values(164,'Armenia');
 insert into gestalt_geography_name (id, name) values(165,'Albania');
 insert into gestalt_geography_name (id, name) values(166,'Vietnam');
 insert into gestalt_geography_name (id, name) values(167,'Argentina');
 insert into gestalt_geography_name (id, name) values(168,'Australia');
 insert into gestalt_geography_name (id, name) values(169,'Cape Verde');
 insert into gestalt_geography_name (id, name) values(170,'Cayman Islands');
 insert into gestalt_geography_name (id, name) values(171,'Christmas Island');
 insert into gestalt_geography_name (id, name) values(172,'Cocos (Keeling) Islands');
 insert into gestalt_geography_name (id, name) values(173,'Comoros');
 insert into gestalt_geography_name (id, name) values(174,'Cook Islands');
 insert into gestalt_geography_name (id, name) values(175,'Curaçao');
 insert into gestalt_geography_name (id, name) values(176,'Cyprus');
 insert into gestalt_geography_name (id, name) values(177,'Dominica');
 insert into gestalt_geography_name (id, name) values(178,'East Timor');
 insert into gestalt_geography_name (id, name) values(179,'Falkland Islands');
 insert into gestalt_geography_name (id, name) values(180,'Faroe Islands');
 insert into gestalt_geography_name (id, name) values(181,'Federated States of Micronesia');
 insert into gestalt_geography_name (id, name) values(182,'Fiji');
 insert into gestalt_geography_name (id, name) values(183,'French Polynesia');
 insert into gestalt_geography_name (id, name) values(184,'French Southern and Antarctic Lands');
 insert into gestalt_geography_name (id, name) values(185,'Gibraltar');
 insert into gestalt_geography_name (id, name) values(186,'Grenada');
 insert into gestalt_geography_name (id, name) values(187,'Guadeloupe');
 insert into gestalt_geography_name (id, name) values(188,'Guam');
 insert into gestalt_geography_name (id, name) values(189,'Guernsey');
 insert into gestalt_geography_name (id, name) values(190,'Heard Island and McDonald Islands');
 insert into gestalt_geography_name (id, name) values(191,'Hong Kong');
 insert into gestalt_geography_name (id, name) values(192,'Isle of Man');
 insert into gestalt_geography_name (id, name) values(193,'Jersey');
 insert into gestalt_geography_name (id, name) values(194,'Kiribati');
 insert into gestalt_geography_name (id, name) values(195,'Macau');
 insert into gestalt_geography_name (id, name) values(196,'Maldives');
 insert into gestalt_geography_name (id, name) values(197,'Malta');
 insert into gestalt_geography_name (id, name) values(198,'Marshall Islands');
 insert into gestalt_geography_name (id, name) values(199,'Martinique');
 insert into gestalt_geography_name (id, name) values(200,'Mayotte');
 insert into gestalt_geography_name (id, name) values(201,'Montserrat');
 insert into gestalt_geography_name (id, name) values(202,'Nauru');
 insert into gestalt_geography_name (id, name) values(203,'New Caledonia');
 insert into gestalt_geography_name (id, name) values(204,'Norfolk Island');
 insert into gestalt_geography_name (id, name) values(205,'Northern Mariana Islands');
 insert into gestalt_geography_name (id, name) values(206,'Palau');
 insert into gestalt_geography_name (id, name) values(207,'Palestine');
 insert into gestalt_geography_name (id, name) values(208,'Bosnia and Herzegovina');
 insert into gestalt_geography_name (id, name) values(209,'Pitcairn Islands');
 insert into gestalt_geography_name (id, name) values(210,'Puerto Rico');
 insert into gestalt_geography_name (id, name) values(211,'Qatar');
 insert into gestalt_geography_name (id, name) values(212,'Réunion');
 insert into gestalt_geography_name (id, name) values(213,'Saint Barthélemy');
 insert into gestalt_geography_name (id, name) values(214,'Saint Helena');
 insert into gestalt_geography_name (id, name) values(215,'Saint Kitts and Nevis');
 insert into gestalt_geography_name (id, name) values(216,'Saint Lucia');
 insert into gestalt_geography_name (id, name) values(217,'Saint Martin');
 insert into gestalt_geography_name (id, name) values(218,'Saint Pierre and Miquelon');
 insert into gestalt_geography_name (id, name) values(219,'Saint Vincent and the Grenadines');
 insert into gestalt_geography_name (id, name) values(220,'Samoa');
 insert into gestalt_geography_name (id, name) values(221,'San Marino');
 insert into gestalt_geography_name (id, name) values(222,'São Tomé and Príncipe');
 insert into gestalt_geography_name (id, name) values(223,'Seychelles');
 insert into gestalt_geography_name (id, name) values(224,'Sint Maarten');
 insert into gestalt_geography_name (id, name) values(225,'Solomon Islands');
 insert into gestalt_geography_name (id, name) values(226,'South Georgia');
 insert into gestalt_geography_name (id, name) values(227,'Svalbard and Jan Mayen');
 insert into gestalt_geography_name (id, name) values(228,'Tokelau');
 insert into gestalt_geography_name (id, name) values(229,'Tonga');
 insert into gestalt_geography_name (id, name) values(230,'Trinidad and Tobago');
 insert into gestalt_geography_name (id, name) values(231,'Turks and Caicos Islands');
 insert into gestalt_geography_name (id, name) values(232,'Tuvalu');
 insert into gestalt_geography_name (id, name) values(233,'United States Minor Outlying Islands');
 insert into gestalt_geography_name (id, name) values(234,'Vanuatu');
 insert into gestalt_geography_name (id, name) values(235,'Wallis and Futuna');
 insert into gestalt_geography_name (id, name) values(236,'Western Sahara');
 insert into gestalt_geography_name (id, name) values(237,'Belgium');
 insert into gestalt_geography_name (id, name) values(238,'The Bahamas');
 insert into gestalt_geography_name (id, name) values(239,'Israel');
 insert into gestalt_geography_name (id, name) values(240,'Aruba');
 insert into gestalt_geography_name (id, name) values(241,'India');
 insert into gestalt_geography_name (id, name) values(242,'Lebanon');
 insert into gestalt_geography_name (id, name) values(243,'Azerbaijan');
 insert into gestalt_geography_name (id, name) values(244,'Republic of Ireland');
 insert into gestalt_geography_name (id, name) values(245,'Indonesia');
 insert into gestalt_geography_name (id, name) values(246,'Panama');
 insert into gestalt_geography_name (id, name) values(247,'Malaysia');
 insert into gestalt_geography_name (id, name) values(248,'North America');
 insert into gestalt_geography_name (id, name) values(249,'South America');
 insert into gestalt_geography_name (id, name) values(250,'Northern Africa');
 insert into gestalt_geography_name (id, name) values(251,'Pacific Islands');
 insert into gestalt_geography_name (id, name) values(252,'Asia');
 insert into gestalt_geography_name (id, name) values(253,'Europe');
 insert into gestalt_geography_name (id, name) values(254,'Middle East');
 insert into gestalt_geography_name (id, name) values(255,'US Virgin Islands');
 insert into gestalt_geography_name (id, name) values(256,'Vatican City State');
