destination: _site/
url: "http://127.0.0.1:4012"
baseurl: "/updates-pdf"
port: 4012
output: pdf
product: updates
print_title: Gestalt's Blog Updates
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true