site_name: Lab41 Gestalt
site_description: To document Lab41's Gestalt
site_author: Lab41
theme: readthedocs
pages: 
- Gestalt: 'index.md'
- Scaffolds: 
    - About: 'scaffolds/index.md'
    - Installation: 'scaffolds/installation.md'
    - Quick Start: 'scaffolds/quickstart.md'
- Prototypes:
    - Desktop: 
      - About: 'prototypes/desktop/index.md'
      - Quick Start: 'prototypes/desktop/quickstart.md'
      - Web App Structure: 'prototypes/desktop/webappstructure.md'
    - Tablet: 
      - About: 'prototypes/tablet/index.md'
      - Quick Start: 'prototypes/tablet/quickstart.md'
      - Web App Structure: 'prototypes/tablet/webappstructure.md'
- Datasets: 
    - BIS: 'datasets/bis.md'
    - OECD: 'datasets/oecd.md'
- Reading Groups:
    - Reading List: 'readings/index.md'
    - 05/27/2016: 'readings/05272016.md'
    - 06/03/2016: 'readings/06032016.md'
