desc "Build Jekyll website"
task :build do
    puts "Building _site, Jekyll's static pages\n"
    system "bundle exec jekyll build"
end

desc "Add _site"
task :commit do
    puts "Adding a commit to update _site"
    system "git add _site && git commit -m \"update _site\""
end

desc "Deploy to GitHub Pages"
task :deploy do
    puts "Deploying to local branch gh-pages\n"
    commit = `git rev-parse --short HEAD`
    message = "Deployed #{commit} with Jekyll version 3.1.6"
    system "git checkout gh-pages && \
            cp -R _site/* ../ && \
            cd .. && \
            rm -rf docs && \
            git add . && \
            git commit -m \"#{message}\""    
    puts "Do NOT forget to push gh-pages to master\n"
end

desc "Build and Deploy to GitHub Pages"
task :publish do 
    Rake::Task["build"].invoke
    Rake::Task["commit"].invoke
    Rake::Task["deploy"].invoke
end
